server:
  port: 8006

spring:
  application:
    name: edu-msm
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #Redis
  redis:
    database: 0 # Redis 数据库索引（默认为 0）
    host: 106.53.108.15 #redis服务器地址
    port: 6379 #端口号
    password: foobared # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        #max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 #连接池最大空闲连接 默认8
        min-idle: 0 #连接池最小空闲连接 默认0