server:
  port: 8005

spring:
  application:
    name: edu-cms
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    url: jdbc:mysql://106.53.108.15:3306/clouddb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/yy_edu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #Redis
  redis:
    database: 0 # Redis 数据库索引（默认为 0）
    host: 106.53.108.15 #redis服务器地址
    port: 6379 #端口号
    password: foobared # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        #max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 #连接池最大空闲连接 默认8
        min-idle: 0 #连接池最小空闲连接 默认0

#mybatis日志F:\IDEA\online-edu\edu-service\src\main\java\com\yy\eduservice\mapper\xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.yy.educms.entity
  mapper-locations: classpath:com/yy/educms/mapper/xml/*.xml

#SpringCloud微服务配置
#Eureka 配置
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true

