#服务端口号
server:
  port: 8002


#服务名
spring:
  application:
    name: edu-vod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true

aliyun:
  vod:
    accessKeyId: "LTAI4GEJpPSkfiakyer4UPKC"
    accessKeySecret: "wr15SmIKfC3NAilCKI1LwQaRdOialf"