server:
  port: 8001

spring:
  application:
    name: edu-service
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://106.53.108.15:3306/clouddb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/yy_edu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatis日志F:\IDEA\online-edu\edu-service\src\main\java\com\yy\eduservice\mapper\xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.yy.eduservice.entity
  mapper-locations: classpath:com/yy/eduservice/mapper/xml/*.xml
aliyun:
  oss:
    endPoint: "oss-cn-chengdu.aliyuncs.com"
    accessKeyId: "LTAI4GEJpPSkfiakyer4UPKC"
    accessKeySecret: "wr15SmIKfC3NAilCKI1LwQaRdOialf"
    bucketName: "yy-edu"

#SpringCloud微服务配置
#Eureka 配置
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
#Feign 配置
#feign:
#  hystrix:
#    enabled: true #feign 开启hystrix支持
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 15000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
